version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:30"
      timezone: "Australia/Perth"
    target-branch: "main"
    reviewers:
      - "ahmedig"
